-- ╔══════════════════════════════════════════════════════════╗
-- ║  TrashTraits.lua                                         ║
-- ║  Auto-generated by dev/scripts/extract-trash-data.lua.   ║
-- ║  DO NOT EDIT BY HAND — re-run the extractor to refresh.  ║
-- ║                                                          ║
-- ║  Per-mob identity fingerprints, ported verbatim from the ║
-- ║  upstream reference's trait rows; the packed hex         ║
-- ║  identity is decoded by the ported bitfield decoder.     ║
-- ║  Keyed by npcID, grouped by dungeon.                     ║
-- ║                                                          ║
-- ║  Schema:                                                 ║
-- ║    KE.TrashTraits[npcID] = {                             ║
-- ║        npcID, mapID, dungeonKey,                         ║
-- ║        identity = { level, sex, power, classID,          ║
-- ║            buffCount, hasCastSkill, noCastSkill,         ║
-- ║            hasCastSpell, hasChannelSpell,                ║
-- ║            hasInterruptFlag, cannotInterrupt, nonElite },║
-- ║        placement,    -- verbatim CSV nameplate slot set  ║
-- ║        castTimeSet,  -- parsed cast-time numbers         ║
-- ║        channelTimeSet,                                   ║
-- ║        spellIDs = { ... },                               ║
-- ║        packedIdentity, -- raw hex, for runtime verify    ║
-- ║    }                                                     ║
-- ╚══════════════════════════════════════════════════════════╝

---@class KE
local KE = select(2, ...)
if not KitnEssentials then return end

KE.TrashTraits = {
    -- ╔══════════════════════════════════════════════════════════╗
    -- ║  Pit of Saron (658)                                      ║
    -- ╚══════════════════════════════════════════════════════════╝

    -- ── Dreadpulse Lich ──
    [252563] = {
        npcID = 252563,
        mapID = 658,
        dungeonKey = "PitOfSaron",
        identity = { level = 91, sex = 2, power = 1, classID = 1, buffCount = 1, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = true, hasInterruptFlag = true, cannotInterrupt = false, nonElite = false },
        placement = "1,2,3",
        castTimeSet = { 4 },
        channelTimeSet = { 6 },
        spellIDs = { 1258820 },
        packedIdentity = 0x3A00016CA11,
    },

    -- ── Glacieth ──
    [252564] = {
        npcID = 252564,
        mapID = 658,
        dungeonKey = "PitOfSaron",
        identity = { level = 91, sex = 1, power = 1, classID = 1, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "3",
        castTimeSet = { 2.5, 5 },
        spellIDs = { 1259188, 1259226 },
        packedIdentity = 0x4A00016C910,
    },

    -- ── Plungetalon Gargoyle ──
    [252606] = {
        npcID = 252606,
        mapID = 658,
        dungeonKey = "PitOfSaron",
        identity = { level = 90, sex = 3, power = 1, classID = 1, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = false, hasChannelSpell = true, hasInterruptFlag = true, cannotInterrupt = false, nonElite = false },
        placement = "1,2",
        channelTimeSet = { 12 },
        spellIDs = { 1258997 },
        packedIdentity = 0x32000168B10,
    },

    -- ── Ymirjar Graveblade ──
    [252610] = {
        npcID = 252610,
        mapID = 658,
        dungeonKey = "PitOfSaron",
        identity = { level = 91, sex = 2, power = 1, classID = 1, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "1,2,3",
        castTimeSet = { 2.5 },
        spellIDs = { 1258439, 1278963 },
        packedIdentity = 0x4A00016CA10,
    },

    -- ── Iceborn Proto-Drake ──
    [257190] = {
        npcID = 257190,
        mapID = 658,
        dungeonKey = "PitOfSaron",
        identity = { level = 91, sex = 1, power = 1, classID = 1, buffCount = 1, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "1,2",
        castTimeSet = { 4.5 },
        spellIDs = { 1278986 },
        packedIdentity = 0x4A00016C911,
    },

    -- ╔══════════════════════════════════════════════════════════╗
    -- ║  Skyreach (1209)                                         ║
    -- ╚══════════════════════════════════════════════════════════╝

    -- ── Solar Construct ──
    [76087] = {
        npcID = 76087,
        mapID = 1209,
        dungeonKey = "Skyreach",
        identity = { level = 91, sex = 1, power = 0, classID = 2, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "2,4",
        castTimeSet = { 2, 3.5 },
        spellIDs = { 1253446, 1253448 },
        packedIdentity = 0x4A00016C120,
    },

    -- ── Dread Raven ──
    [76149] = {
        npcID = 76149,
        mapID = 1209,
        dungeonKey = "Skyreach",
        identity = { level = 91, sex = 1, power = 1, classID = 1, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "1,4",
        castTimeSet = { 2.5, 3 },
        spellIDs = { 1254566, 1258174 },
        packedIdentity = 0x4A00016C910,
    },

    -- ── Suntalon Tamer ──
    [76154] = {
        npcID = 76154,
        mapID = 1209,
        dungeonKey = "Skyreach",
        identity = { level = 90, sex = 1, power = 0, classID = 2, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = false, nonElite = false },
        placement = "3",
        castTimeSet = { 2.5 },
        spellIDs = { 1254686 },
        packedIdentity = 0xA000168120,
    },

    -- ── Solar Elemental ──
    [78933] = {
        npcID = 78933,
        mapID = 1209,
        dungeonKey = "Skyreach",
        identity = { level = 91, sex = 1, power = 0, classID = 2, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = true, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "2,4",
        castTimeSet = { 2 },
        channelTimeSet = { 6 },
        spellIDs = { 1254355, 1258217 },
        packedIdentity = 0x5A00016C120,
    },

    -- ── Adorned Bladetalon ──
    [79303] = {
        npcID = 79303,
        mapID = 1209,
        dungeonKey = "Skyreach",
        identity = { level = 91, sex = 1, power = 1, classID = 1, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "1,4",
        castTimeSet = { 2, 3 },
        spellIDs = { 1254380, 1254460 },
        packedIdentity = 0x4A00016C910,
    },

    -- ╔══════════════════════════════════════════════════════════╗
    -- ║  Seat of the Triumvirate (1753)                          ║
    -- ╚══════════════════════════════════════════════════════════╝

    -- ── Umbral War-Adept ──
    [122421] = {
        npcID = 122421,
        mapID = 1753,
        dungeonKey = "SeatOfTriumvirate",
        identity = { level = 91, sex = 2, power = 1, classID = 1, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "2",
        castTimeSet = { 2 },
        spellIDs = { 1280326 },
        packedIdentity = 0x4A00016CA10,
    },

    -- ── Grand Shadow-Weaver ──
    [122423] = {
        npcID = 122423,
        mapID = 1753,
        dungeonKey = "SeatOfTriumvirate",
        identity = { level = 91, sex = 3, power = 0, classID = 2, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "3,4",
        castTimeSet = { 2 },
        spellIDs = { 1262508, 1264286 },
        packedIdentity = 0x4A00016C320,
    },

    -- ── Rift Warden ──
    [122571] = {
        npcID = 122571,
        mapID = 1753,
        dungeonKey = "SeatOfTriumvirate",
        identity = { level = 91, sex = 1, power = 1, classID = 1, buffCount = 1, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "2",
        castTimeSet = { 3 },
        spellIDs = { 1280330 },
        packedIdentity = 0x4A00016C911,
    },

    -- ── Merciless Subjugator ──
    [124171] = {
        npcID = 124171,
        mapID = 1753,
        dungeonKey = "SeatOfTriumvirate",
        identity = { level = 91, sex = 3, power = 0, classID = 2, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "1,2",
        castTimeSet = { 2 },
        spellIDs = { 1262506, 1262509 },
        packedIdentity = 0x4A00016C320,
    },

    -- ── Void-Infused Destroyer ──
    [252756] = {
        npcID = 252756,
        mapID = 1753,
        dungeonKey = "SeatOfTriumvirate",
        identity = { level = 91, sex = 1, power = 1, classID = 1, buffCount = 1, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "3,4",
        castTimeSet = { 3, 4.5 },
        spellIDs = { 1262335, 1262429 },
        packedIdentity = 0x4A00016C911,
    },

    -- ╔══════════════════════════════════════════════════════════╗
    -- ║  Algeth'ar Academy (2526)                                ║
    -- ╚══════════════════════════════════════════════════════════╝

    -- ── Alpha Eagle ──
    [192333] = {
        npcID = 192333,
        mapID = 2526,
        dungeonKey = "AlgetharAcademy",
        identity = { level = 91, sex = 1, power = 1, classID = 1, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "2",
        castTimeSet = { 3, 3.5 },
        spellIDs = { 377383, 377389 },
        packedIdentity = 0x4A00016C910,
    },

    -- ── Guardian Sentry ──
    [192680] = {
        npcID = 192680,
        mapID = 2526,
        dungeonKey = "AlgetharAcademy",
        identity = { level = 91, sex = 1, power = 1, classID = 1, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "2",
        castTimeSet = { 2.5, 3, 5.5 },
        spellIDs = { 377912, 377991, 378003 },
        packedIdentity = 0x4A00016C910,
    },

    -- ── Algeth'ar Echoknight ──
    [196200] = {
        npcID = 196200,
        mapID = 2526,
        dungeonKey = "AlgetharAcademy",
        identity = { level = 91, sex = 3, power = 1, classID = 1, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "4",
        castTimeSet = { 3 },
        spellIDs = { 1270356 },
        packedIdentity = 0x4A00016CB10,
    },

    -- ── Vicious Ravager ──
    [196671] = {
        npcID = 196671,
        mapID = 2526,
        dungeonKey = "AlgetharAcademy",
        identity = { level = 91, sex = 1, power = 1, classID = 1, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = true, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "3",
        castTimeSet = { 2.5, 3.5 },
        channelTimeSet = { 2.5 },
        spellIDs = { 388942, 388976 },
        packedIdentity = 0x5A00016C910,
    },

    -- ── Vile Lasher ──
    [197219] = {
        npcID = 197219,
        mapID = 2526,
        dungeonKey = "AlgetharAcademy",
        identity = { level = 91, sex = 1, power = 1, classID = 1, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "1",
        castTimeSet = { 3 },
        spellIDs = { 1282244 },
        packedIdentity = 0x4A00016C910,
    },

    -- ╔══════════════════════════════════════════════════════════╗
    -- ║  Windrunner Spire (2805)                                 ║
    -- ╚══════════════════════════════════════════════════════════╝

    -- ── Territorial Dragonhawk ──
    [232056] = {
        npcID = 232056,
        mapID = 2805,
        dungeonKey = "WindrunnerSpire",
        identity = { level = 90, sex = 1, power = 1, classID = 1, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = false, hasChannelSpell = true, hasInterruptFlag = false, cannotInterrupt = false, nonElite = false },
        placement = "2493,2494",
        channelTimeSet = { 9 },
        spellIDs = { 1216848 },
        packedIdentity = 0x12000168910,
    },

    -- ── Apex Lynx ──
    [232063] = {
        npcID = 232063,
        mapID = 2805,
        dungeonKey = "WindrunnerSpire",
        identity = { level = 91, sex = 1, power = 1, classID = 1, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "2493,2494",
        castTimeSet = { 3, 3.5 },
        spellIDs = { 1216985, 1217010 },
        packedIdentity = 0x4A00016C910,
    },

    -- ── Spellguard Magus ──
    [232113] = {
        npcID = 232113,
        mapID = 2805,
        dungeonKey = "WindrunnerSpire",
        identity = { level = 91, sex = 2, power = 0, classID = 2, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = true, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "2492",
        castTimeSet = { 3 },
        channelTimeSet = { 6 },
        spellIDs = { 1216250 },
        packedIdentity = 0x5A00016C220,
    },

    -- ── Phalanx Breaker ──
    [232122] = {
        npcID = 232122,
        mapID = 2805,
        dungeonKey = "WindrunnerSpire",
        identity = { level = 91, sex = 1, power = 0, classID = 2, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "2493,2494,2496,2498",
        castTimeSet = { 5 },
        spellIDs = { 471643, 471648 },
        packedIdentity = 0x4A00016C120,
    },

    -- ── Phantasmal Mystic ──
    [232146] = {
        npcID = 232146,
        mapID = 2805,
        dungeonKey = "WindrunnerSpire",
        identity = { level = 91, sex = 2, power = 0, classID = 2, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = true, cannotInterrupt = false, nonElite = false },
        placement = "2493,2494,2496,2498,2537",
        castTimeSet = { 2.5, 3, 4 },
        spellIDs = { 1270618 },
        packedIdentity = 0x2A00016C220,
    },

    -- ── Devoted Woebringer ──
    [232175] = {
        npcID = 232175,
        mapID = 2805,
        dungeonKey = "WindrunnerSpire",
        identity = { level = 91, sex = 3, power = 1, classID = 1, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = true, hasInterruptFlag = true, cannotInterrupt = false, nonElite = false },
        placement = "2496,2497",
        castTimeSet = { 2.5 },
        channelTimeSet = { 16 },
        spellIDs = { 473672 },
        packedIdentity = 0x3A00016CB10,
    },

    -- ── Flesh Behemoth ──
    [232176] = {
        npcID = 232176,
        mapID = 2805,
        dungeonKey = "WindrunnerSpire",
        identity = { level = 91, sex = 1, power = 1, classID = 1, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "2496,2497",
        castTimeSet = { 2.5, 3.5 },
        spellIDs = { 473776, 1277799 },
        packedIdentity = 0x4A00016C910,
    },

    -- ── Bloated Lasher ──
    [236894] = {
        npcID = 236894,
        mapID = 2805,
        dungeonKey = "WindrunnerSpire",
        identity = { level = 91, sex = 1, power = 3, classID = 4, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = true, cannotInterrupt = false, nonElite = false },
        placement = "2493,2494",
        castTimeSet = { 2.5, 4 },
        spellIDs = { 1216963 },
        packedIdentity = 0x2A00016D940,
    },

    -- ╔══════════════════════════════════════════════════════════╗
    -- ║  Magisters' Terrace (2811)                               ║
    -- ╚══════════════════════════════════════════════════════════╝

    -- ── Arcane Sentry ──
    [234062] = {
        npcID = 234062,
        mapID = 2811,
        dungeonKey = "MagistersTerrace",
        identity = { level = 91, sex = 1, power = 3, classID = 4, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "1,2",
        castTimeSet = { 2, 3 },
        spellIDs = { 473258, 1282050, 1282055 },
        packedIdentity = 0x4A00016D940,
    },

    -- ── Devouring Tyrant ──
    [234066] = {
        npcID = 234066,
        mapID = 2811,
        dungeonKey = "MagistersTerrace",
        identity = { level = 91, sex = 1, power = 1, classID = 1, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "3,4",
        castTimeSet = { 2.5 },
        spellIDs = { 1264687 },
        packedIdentity = 0x4A00016C910,
    },

    -- ── Shadowrift Voidcaller ──
    [234068] = {
        npcID = 234068,
        mapID = 2811,
        dungeonKey = "MagistersTerrace",
        identity = { level = 91, sex = 1, power = 3, classID = 4, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = true, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "3,4",
        castTimeSet = { 3 },
        channelTimeSet = { 3 },
        spellIDs = { 1255462, 1265977 },
        packedIdentity = 0x5A00016D940,
    },

    -- ── Runed Spellbreaker ──
    [240973] = {
        npcID = 240973,
        mapID = 2811,
        dungeonKey = "MagistersTerrace",
        identity = { level = 91, sex = 3, power = 0, classID = 2, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "2",
        castTimeSet = { 3 },
        spellIDs = { 1244907, 1283901 },
        packedIdentity = 0x4A00016C320,
    },

    -- ── Blazing Pyromancer ──
    [251861] = {
        npcID = 251861,
        mapID = 2811,
        dungeonKey = "MagistersTerrace",
        identity = { level = 91, sex = 3, power = 0, classID = 2, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = true, cannotInterrupt = false, nonElite = false },
        placement = "1",
        castTimeSet = { 2, 3.5, 4 },
        spellIDs = { 1254301, 1254336 },
        packedIdentity = 0x2A00016C320,
    },

    -- ╔══════════════════════════════════════════════════════════╗
    -- ║  Maisara Caverns (2874)                                  ║
    -- ╚══════════════════════════════════════════════════════════╝

    -- ── Hulking Juggernaut ──
    [248678] = {
        npcID = 248678,
        mapID = 2874,
        dungeonKey = "MaisaraCaverns",
        identity = { level = 91, sex = 1, power = 1, classID = 1, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "1",
        castTimeSet = { 2, 3.5 },
        spellIDs = { 1256047, 1256059 },
        packedIdentity = 0x4A00016C910,
    },

    -- ── Dread Souleater ──
    [248686] = {
        npcID = 248686,
        mapID = 2874,
        dungeonKey = "MaisaraCaverns",
        identity = { level = 91, sex = 3, power = 0, classID = 2, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "1",
        castTimeSet = { 1.5, 2 },
        spellIDs = { 1257155 },
        packedIdentity = 0x4A00016C320,
    },

    -- ── Hexbound Eagle ──
    [249020] = {
        npcID = 249020,
        mapID = 2874,
        dungeonKey = "MaisaraCaverns",
        identity = { level = 90, sex = 1, power = 1, classID = 1, buffCount = 1, hasCastSkill = true, noCastSkill = false, hasCastSpell = false, hasChannelSpell = true, hasInterruptFlag = false, cannotInterrupt = false, nonElite = false },
        placement = "1",
        channelTimeSet = { 5 },
        spellIDs = { 1257781 },
        packedIdentity = 0x12000168911,
    },

    -- ── Hollow Soulrender ──
    [249024] = {
        npcID = 249024,
        mapID = 2874,
        dungeonKey = "MaisaraCaverns",
        identity = { level = 91, sex = 1, power = 0, classID = 2, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = true, hasInterruptFlag = true, cannotInterrupt = false, nonElite = false },
        placement = "2,3",
        castTimeSet = { 2.5, 3.2 },
        channelTimeSet = { 6 },
        spellIDs = { 1259677, 1271623 },
        packedIdentity = 0x3A00016C120,
    },

    -- ── Bound Defender ──
    [249025] = {
        npcID = 249025,
        mapID = 2874,
        dungeonKey = "MaisaraCaverns",
        identity = { level = 91, sex = 1, power = 1, classID = 1, buffCount = 1, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = true, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "2,3",
        castTimeSet = { 3 },
        channelTimeSet = { 6 },
        spellIDs = { 1257546, 1259651 },
        packedIdentity = 0x5A00016C911,
    },

    -- ── Restless Gnarldin ──
    [249030] = {
        npcID = 249030,
        mapID = 2874,
        dungeonKey = "MaisaraCaverns",
        identity = { level = 91, sex = 2, power = 1, classID = 1, buffCount = 1, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "2,3",
        castTimeSet = { 3 },
        spellIDs = { 1257895, 1259631 },
        packedIdentity = 0x4A00016CA11,
    },

    -- ── Hex Guardian ──
    [253302] = {
        npcID = 253302,
        mapID = 2874,
        dungeonKey = "MaisaraCaverns",
        identity = { level = 91, sex = 1, power = 0, classID = 2, buffCount = 1, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "1",
        castTimeSet = { 2.5, 3.5 },
        spellIDs = { 1258475, 1258806 },
        packedIdentity = 0x4A00016C121,
    },

    -- ── Rokh'zal ──
    [253683] = {
        npcID = 253683,
        mapID = 2874,
        dungeonKey = "MaisaraCaverns",
        identity = { level = 91, sex = 2, power = 0, classID = 2, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = true, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "2",
        castTimeSet = { 2.5 },
        channelTimeSet = { 1 },
        spellIDs = { 1259786, 1262241 },
        packedIdentity = 0x5A00016C220,
    },

    -- ╔══════════════════════════════════════════════════════════╗
    -- ║  Nexus-Point Xenas (2915)                                ║
    -- ╚══════════════════════════════════════════════════════════╝

    -- ── Lingering Image ──
    [241642] = {
        npcID = 241642,
        mapID = 2915,
        dungeonKey = "NexusPointXenas",
        identity = { level = 91, sex = 2, power = 0, classID = 2, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "16573,16574,16576",
        castTimeSet = { 3, 4.5 },
        spellIDs = { 1257701, 1264354, 1281657 },
        packedIdentity = 0x4A00016C220,
    },

    -- ── Duskfright Herald ──
    [241660] = {
        npcID = 241660,
        mapID = 2915,
        dungeonKey = "NexusPointXenas",
        identity = { level = 91, sex = 1, power = 0, classID = 8, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = true, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "16575",
        castTimeSet = { 0.6, 3, 3.4 },
        channelTimeSet = { 604800 },
        spellIDs = { 1252062, 1252076 },
        packedIdentity = 0x5A00016C180,
    },

    -- ── Circuit Seer ──
    [248373] = {
        npcID = 248373,
        mapID = 2915,
        dungeonKey = "NexusPointXenas",
        identity = { level = 91, sex = 1, power = 0, classID = 8, buffCount = 1, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = true, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "16574",
        castTimeSet = { 1.5 },
        channelTimeSet = { 7.5, 2.5 },
        spellIDs = { 1249801, 1262720 },
        packedIdentity = 0x5A00016C181,
    },

    -- ── Null Sentinel ──
    [248502] = {
        npcID = 248502,
        mapID = 2915,
        dungeonKey = "NexusPointXenas",
        identity = { level = 91, sex = 1, power = 1, classID = 1, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = false, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "16575",
        castTimeSet = { 1.5, 4.5 },
        spellIDs = { 1252406, 1252417 },
        packedIdentity = 0x4A00016C910,
    },

    -- ── Dreadflail ──
    [248506] = {
        npcID = 248506,
        mapID = 2915,
        dungeonKey = "NexusPointXenas",
        identity = { level = 91, sex = 1, power = 1, classID = 1, buffCount = 0, hasCastSkill = true, noCastSkill = false, hasCastSpell = true, hasChannelSpell = true, hasInterruptFlag = false, cannotInterrupt = true, nonElite = false },
        placement = "16575",
        castTimeSet = { 1.5, 2.4 },
        channelTimeSet = { 8.5 },
        spellIDs = { 1252436, 1252622 },
        packedIdentity = 0x5A00016C910,
    },
}
