-- KitnEssentials namespace
---@class KE
local KE = select(2, ...)

-- Default position template
local function DefaultPosition(xOff, yOff)
    return {
        AnchorFrom = "CENTER",
        AnchorTo = "CENTER",
        XOffset = xOff or 0,
        YOffset = yOff or 0,
    }
end

-- Default font shadow template
local function DefaultFontShadow()
    return {
        Enabled = false,
        OffsetX = 0,
        OffsetY = 0,
        Color = { 0, 0, 0, 0 },
    }
end

-- Default backdrop template
local function DefaultBackdrop()
    return {
        Enabled = false,
        Color = { 0, 0, 0, 0.6 },
        BorderColor = { 0, 0, 0, 1 },
        BorderSize = 1,
        bgWidth = 5,
        bgHeight = 5,
    }
end

local Defaults = {
    global = {
        UseGlobalProfile = false,
        GlobalProfile = "Default",

        GUIState = {
            frame = {
                point = nil,
                relativePoint = nil,
                xOffset = nil,
                yOffset = nil,
                width = nil,
                height = nil,
            },
            selectedGroupId = nil,
            selectedTab = nil,
            minimized = false,
        },
    },
    profile = {
        -- Minimap Icon
        Minimap = {
            hide = false,
        },

        -- ElvUI Integration
        UseElvUI = {
            Enabled = true,
        },

        ----------------------------------------------------------------
        -- COMBAT MODULES
        ----------------------------------------------------------------

        CombatTimer = {
            Enabled = false,
            ShowChatMessage = true,
            Format = "MM:SS",
            BracketStyle = "square",
            FontSize = 28,
            FontFace = "Expressway",
            FontOutline = "SOFTOUTLINE",
            FontShadow = DefaultFontShadow(),
            ColorInCombat = { 1, 1, 1, 1 },
            ColorOutOfCombat = { 1, 1, 1, 0.7 },
            anchorFrameType = "UIPARENT",
            ParentFrame = "UIParent",
            Strata = "HIGH",
            Position = DefaultPosition(0, -100),
            Backdrop = DefaultBackdrop(),
        },

        CombatCross = {
            Enabled = false,
            Strata = "HIGH",
            anchorFrameType = "UIPARENT",
            ParentFrame = "UIParent",
            Position = DefaultPosition(0, -10),
            ColorMode = "custom",
            Color = { 0, 1, 0.169, 1 },
            Thickness = 22,
            Outline = true,
        },

        CombatRes = {
            Enabled = false,
            Strata = "HIGH",
            anchorFrameType = "UIPARENT",
            ParentFrame = "UIParent",
            Position = DefaultPosition(0, -60),
            FontSize = 16,
            FontFace = "Expressway",
            FontOutline = "SOFTOUTLINE",
            TextSpacing = 4,
            GrowthDirection = "RIGHT",
            SeparatorColor = { 1, 1, 1, 1 },
            TimerColor = { 1, 1, 1, 1 },
            ChargeAvailableColor = { 0.3, 1, 0.3, 1 },
            ChargeUnavailableColor = { 1, 0.3, 0.3, 1 },
            Separator = "|",
            SeparatorCharges = "CR:",
            BracketStyle = "square",
            Backdrop = DefaultBackdrop(),
        },

        CombatTexts = {
            Enabled = false,
            Strata = "HIGH",
            anchorFrameType = "UIPARENT",
            ParentFrame = "UIParent",
            FontFace = "Expressway",
            FontSize = 16,
            FontOutline = "SOFTOUTLINE",
            Position = DefaultPosition(0, -80),
            Duration = 1.5,
            Spacing = 4,
            EnterEnabled = true,
            EnterCombatText = "+ Combat",
            EnterColor = { 1, 0.1, 0.1, 1 },
            ExitEnabled = true,
            ExitCombatText = "- Combat",
            ExitColor = { 0.1, 1, 0.1, 1 },
            DurabilityEnabled = true,
            DurabilityText = "LOW DURABILITY",
            DurabilityColor = { 1, 0.3, 0.3, 1 },
            DurabilityThreshold = 25,
            Backdrop = DefaultBackdrop(),
        },

        CursorCircle = {
            Enabled = false,
            Size = 40,
            Texture = "Circle 3",
            Color = { 1, 1, 1, 1 },
            ColorMode = "theme",
            VisibilityMode = "always",
            UseUpdateInterval = false,
            UpdateInterval = 0.016,
            GCD = {
                Mode = "integrated",
                Size = 25,
                Texture = "Circle 5",
                SwipeColorMode = "custom",
                SwipeColor = { 1, 1, 1, 1 },
                Reverse = true,
                HideOutOfCombat = false,
                RingColorMode = "theme",
                RingColor = { 1, 1, 1, 1 },
            },
        },

        PetStatusText = {
            Enabled = false,
            Strata = "HIGH",
            anchorFrameType = "UIPARENT",
            ParentFrame = "UIParent",
            Position = DefaultPosition(0, -120),
            FontSize = 14,
            FontFace = "Expressway",
            FontOutline = "SOFTOUTLINE",
            PetMissing = "PET MISSING",
            PetDead = "PET DEAD",
            PetPassive = "PET PASSIVE",
            MissingColor = { 1, 0.82, 0, 1 },
            DeadColor = { 1, 0.2, 0.2, 1 },
            PassiveColor = { 0.3, 0.7, 1, 1 },
        },

        GatewayAlert = {
            Enabled = false,
            Strata = "HIGH",
            anchorFrameType = "UIPARENT",
            ParentFrame = "UIParent",
            Position = DefaultPosition(0, 150),
            FontSize = 16,
            FontFace = "Expressway",
            FontOutline = "SOFTOUTLINE",
            Color = { 1, 0.82, 0, 1 },
        },

        TargetCastbar = {
            Enabled = false,
            Width = 250,
            Height = 20,
            Strata = "HIGH",
            anchorFrameType = "UIPARENT",
            ParentFrame = "UIParent",
            Position = DefaultPosition(0, -200),
            FontSize = 12,
            FontFace = "Expressway",
            FontOutline = "OUTLINE",
            StatusBarTexture = "KitnUI",
            CastingColor = { 1, 0.7, 0, 1 },
            ChannelingColor = { 0, 0.7, 1, 1 },
            EmpoweringColor = { 0.8, 0.4, 1, 1 },
            NotInterruptibleColor = { 0.7, 0.7, 0.7, 1 },
            HideNotInterruptible = false,
            TextColor = { 1, 1, 1, 1 },
            BackdropColor = { 0, 0, 0, 0.8 },
            BorderColor = { 0, 0, 0, 1 },
            HoldTimer = {
                Enabled = true,
                Duration = 0.5,
                InterruptedColor = { 0.1, 0.8, 0.1, 1 },
                SuccessColor = { 0.8, 0.1, 0.1, 1 },
            },
            KickIndicator = {
                Enabled = true,
                ReadyColor = { 0.1, 0.8, 0.1, 1 },
                NotReadyColor = { 0.5, 0.5, 0.5, 1 },
                TickColor = { 1, 1, 1, 1 },
            },
        },

        FocusCastbar = {
            Enabled = false,
            Width = 200,
            Height = 18,
            Strata = "HIGH",
            anchorFrameType = "UIPARENT",
            ParentFrame = "UIParent",
            Position = DefaultPosition(0, 200),
            FontSize = 11,
            FontFace = "Expressway",
            FontOutline = "OUTLINE",
            StatusBarTexture = "KitnUI",
            CastingColor = { 1, 0.7, 0, 1 },
            ChannelingColor = { 0, 0.7, 1, 1 },
            EmpoweringColor = { 0.8, 0.4, 1, 1 },
            NotInterruptibleColor = { 0.7, 0.7, 0.7, 1 },
            HideNotInterruptible = false,
            TextColor = { 1, 1, 1, 1 },
            BackdropColor = { 0, 0, 0, 0.8 },
            BorderColor = { 0, 0, 0, 1 },
            HoldTimer = {
                Enabled = true,
                Duration = 0.5,
                InterruptedColor = { 0.1, 0.8, 0.1, 1 },
                SuccessColor = { 0.8, 0.1, 0.1, 1 },
            },
            KickIndicator = {
                Enabled = true,
                ReadyColor = { 0.1, 0.8, 0.1, 1 },
                NotReadyColor = { 0.5, 0.5, 0.5, 1 },
                TickColor = { 1, 1, 1, 1 },
            },
            TargetNames = {
                Anchor = "RIGHT",
                XOffset = 0,
                YOffset = 14,
                FontSize = 12,
            },
        },

        RangeChecker = {
            Enabled = false,
            CombatOnly = false,
            UpdateThrottle = 0.1,
            MaxRange = 40,
            ColorOne = { 1, 0, 0 },
            ColorTwo = { 1, 0.42, 0 },
            ColorThree = { 1, 0.82, 0 },
            ColorFour = { 0, 1, 0 },
            FontFace = "Expressway",
            FontSize = 24,
            FontOutline = "SOFTOUTLINE",
            Strata = "HIGH",
            anchorFrameType = "UIPARENT",
            ParentFrame = "UIParent",
            Position = DefaultPosition(0, -140),
        },

        TimeSpiral = {
            Enabled = false,
            IconSize = 40,
            ShowText = true,
            TextLabel = "FREE",
            TextColor = { 0, 1, 0, 1 },
            GlowEnabled = true,
            GlowType = "proc",
            GlowColor = { 0, 1, 0, 1 },
            FontFace = "Expressway",
            FontSize = 14,
            FontOutline = "SOFTOUTLINE",
            Strata = "HIGH",
            anchorFrameType = "UIPARENT",
            ParentFrame = "UIParent",
            Position = DefaultPosition(0, -160),
        },

        ----------------------------------------------------------------
        -- QOL MODULES
        ----------------------------------------------------------------

        Automation = {
            Enabled = false,
            SkipCinematics = true,
            HideTalkingHead = true,
            AutoSellJunk = true,
            AutoRepair = true,
            UseGuildFunds = true,
            AutoRoleCheck = true,
            AutoFillDelete = true,
            AutoLoot = true,
            AutoAcceptQuests = false,
            AutoTurnInQuests = false,
            QuestModifier = "SHIFT",
            AutoDeclineDuels = false,
            AutoDeclinePetBattles = false,
            AHCurrentExpansion = false,
            -- CVars (merged) - boolean
            CVarsEnabled = true,
            enableFloatingCombatText = nil,
            floatingCombatTextCombatDamage_v2 = nil,
            floatingCombatTextCombatHealing_v2 = nil,
            floatingCombatTextReactives_v2 = nil,
            findYourselfModeOutline = nil,
            occludedSilhouettePlayer = nil,
            ffxDeath = nil,
            ffxGlow = nil,
            ResampleAlwaysSharpen = nil,
            nameplateShowOnlyNameForFriendlyPlayerUnits = nil,
            nameplateUseClassColorForFriendlyPlayerUnitNames = nil,
            -- CVars (merged) - sliders
            SpellQueueWindow = nil,
            RAIDWaterDetail = nil,
            RAIDweatherDensity = nil,
            autoLootRate = nil,
        },

        CopyAnything = {
            Enabled = false,
            mod = "ctrl",
            key = "C",
        },

        DragonRiding = {
            Enabled = false,
            HideWhenGrounded = false,
            Width = 252,
            BarHeight = 12,
            Spacing = 1,
            SpeedFontSize = 14,
            FontFace = "Expressway",
            anchorFrameType = "UIPARENT",
            ParentFrame = "UIParent",
            Strata = "MEDIUM",
            Position = DefaultPosition(0, 220),
            Colors = {
                Vigor = { 0.898, 0.063, 0.224, 1 },
                VigorThrill = { 0.2, 0.8, 0.2, 1 },
                WhirlingSurge = { 0.6, 0.4, 0.9, 1 },
                WhirlingSurgeCD = { 0.3, 0.3, 0.3, 1 },
                SecondWind = { 0.3, 0.7, 1, 1 },
                SecondWindCD = { 0.3, 0.3, 0.3, 1 },
            },
        },

        MissingBuffs = {
            Enabled = false,
            Consumables = {
                Flask = { Enabled = true, LoadCondition = "ANYGROUP" },
                Food = { Enabled = true, LoadCondition = "ANYGROUP" },
                MHEnchant = { Enabled = true, LoadCondition = "ANYGROUP" },
                OHEnchant = { Enabled = true, LoadCondition = "ANYGROUP" },
                Rune = { Enabled = true, LoadCondition = "RAID" },
                RaidBuffs = { Enabled = true, LoadCondition = "ANYGROUP" },
                Poisons = { Enabled = true, LoadCondition = "ALWAYS" },
            },
            RaidBuffDisplay = {
                IconSize = 48,
                IconSpacing = 1,
                FontFace = "Expressway",
                FontSize = 20,
                FontOutline = "SOFTOUTLINE",
                Strata = "HIGH",
                anchorFrameType = "UIPARENT",
                ParentFrame = "UIParent",
                Position = DefaultPosition(0, -380),
            },
            Stances = {
                Enabled = true,
                HideInRestedArea = false,
                WARRIOR = {
                    Enabled = true,
                    ArmsEnabled = true, Arms = "386164", ArmsReverseIcon = true,
                    FuryEnabled = true, Fury = "386196", FuryReverseIcon = true,
                    ProtectionEnabled = false, Protection = "386208", ProtectionReverseIcon = false,
                },
                PALADIN = {
                    Enabled = true,
                    HolyEnabled = false, Holy = "465", HolyReverseIcon = false,
                    ProtectionEnabled = false, Protection = "465", ProtectionReverseIcon = false,
                    RetributionEnabled = false, Retribution = "32223", RetributionReverseIcon = false,
                },
                DRUID = {
                    Enabled = true,
                    BalanceEnabled = true, Balance = "24858", BalanceReverseIcon = false,
                    FeralEnabled = true, Feral = "768", FeralReverseIcon = false,
                    GuardianEnabled = true, Guardian = "5487", GuardianReverseIcon = false,
                },
                PRIEST = {
                    ShadowEnabled = true, ShadowReverseIcon = false,
                },
                EVOKER = {
                    Enabled = true,
                    AugmentationEnabled = false, Augmentation = "403264", AugmentationReverseIcon = false,
                },
            },
            StanceDisplay = {
                Enabled = true,
                IconSize = 36,
                FontFace = "Expressway",
                FontSize = 13,
                FontOutline = "SOFTOUTLINE",
                Strata = "HIGH",
                anchorFrameType = "UIPARENT",
                ParentFrame = "UIParent",
                Position = DefaultPosition(0, -110),
            },
            StanceText = {
                Enabled = false,
                FontFace = "Expressway",
                FontSize = 14,
                FontOutline = "SOFTOUTLINE",
                Strata = "HIGH",
                anchorFrameType = "UIPARENT",
                ParentFrame = "UIParent",
                Position = DefaultPosition(-250, -130),
                WARRIOR = {
                    ["386164"] = { Enabled = true, Text = "BATTLE", Color = { 1, 0, 0, 1 } },
                    ["386196"] = { Enabled = true, Text = "BER", Color = { 1, 0, 0, 1 } },
                    ["386208"] = { Enabled = true, Text = "DEF", Color = { 0.3, 0.7, 1, 1 } },
                },
                PALADIN = {
                    ["465"] = { Enabled = true, Text = "DEVO", Color = { 0.3, 0.7, 1, 1 } },
                    ["317920"] = { Enabled = true, Text = "CONC", Color = { 0.9, 0.5, 1, 1 } },
                    ["32223"] = { Enabled = true, Text = "CRU", Color = { 1, 0.8, 0.3, 1 } },
                },
            },
        },

        HuntersMark = {
            Enabled = false,
            Strata = "HIGH",
            anchorFrameType = "UIPARENT",
            ParentFrame = "UIParent",
            Position = DefaultPosition(0, 120),
            FontSize = 16,
            FontFace = "Expressway",
            FontOutline = "OUTLINE",
            Color = { 1, 0.82, 0, 1 },
        },

        HideBars = {
            Enabled = false,
            Keybind = "",
            Bars = {
                [1] = true, [2] = false, [3] = false,
                [4] = true, [5] = true, [6] = true,
            },
        },

        SlashCommands = {
            CDMEnabled = true,
            SetPITargetEnabled = true,
            RLEnabled = true,
            FSEnabled = true,
            LeavePartyEnabled = true,
            ResetInstancesEnabled = true,
            MuteEnabled = true,
            MusicEnabled = true,
            PITrinket1 = true,
            PITrinket2 = false,
            PIVampiricEmbrace = true,
            PIRacial = "Ancestral Call",
            PIConsumable = "item:241309",
            PICustom = "",
        },

        Recuperate = {
            Enabled = false,
            Size = 40,
            anchorFrameType = "UIPARENT",
            ParentFrame = "UIParent",
            Strata = "MEDIUM",
            Position = DefaultPosition(0, -250),
        },

        ----------------------------------------------------------------
        -- SKINNING MODULES (disabled when ElvUI active)
        ----------------------------------------------------------------

        Skinning = {
            Tooltips = {
                Enabled = false,
                BackgroundColor = { 0, 0, 0, 0.8 },
                BorderColor = { 0, 0, 0, 1 },
                BorderSize = 1,
                HideHealthBar = true,
                FontFace = "Expressway",
                FontOutline = "OUTLINE",
                NameFontSize = 17,
                GuildFontSize = 14,
                RaceLevelFontSize = 14,
                SpecFontSize = 14,
                FactionFontSize = 14,
                Position = {
                    AnchorFrom = "BOTTOMRIGHT",
                    AnchorTo = "BOTTOMRIGHT",
                    XOffset = -1,
                    YOffset = 350,
                },
            },
            Chat         = { Enabled = false },
            Messages = {
                Enabled = false,
                Font = "Expressway",
                FontOutline = "OUTLINE",
                UIErrorsFrame = {
                    Hide = false,
                    Size = 14,
                    Position = {
                        Anchor = "TOP",
                        X = 0,
                        Y = -281,
                    },
                },
                ActionStatusText = {
                    Hide = false,
                    Size = 14,
                    Position = {
                        Anchor = "TOP",
                        X = 0,
                        Y = -251,
                    },
                },
                ChatBubbles = {
                    Enabled = true,
                    Size = 8,
                },
                ObjectiveTracker = {
                    Enabled = true,
                    QuestTextSize = 12,
                    QuestTitleSize = 13,
                },
                ZoneText = {
                    Hide = false,
                    SubZone = {
                        Size = 20,
                    },
                    MainZone = {
                        Size = 40,
                        Anchor = "TOP",
                        X = 0,
                        Y = -200,
                    },
                },
            },
            Mouseover = {
                Enabled = false,
                Alpha = 0.0,
                FadeInDuration = 0.2,
                FadeOutDuration = 1,
                BagMouseover = {
                    Enabled = true,
                },
            },
            MicroMenu = {
                Enabled = false,
                ButtonWidth = 23,
                ButtonHeight = 31,
                ButtonSpacing = -4,
                BackdropSpacing = 0,
                ShowBackdrop = true,
                BackdropColor = { 0, 0, 0, 0.8 },
                BackdropBorderColor = { 0, 0, 0, 1 },
                anchorFrameType = "SELECTFRAME",
                ParentFrame = "Minimap",
                Strata = "HIGH",
                Position = {
                    AnchorFrom = "TOP",
                    AnchorTo = "BOTTOM",
                    XOffset = 0,
                    YOffset = -1,
                },
                Mouseover = {
                    Enabled = false,
                    Alpha = 0.0,
                    FadeInDuration = 0.2,
                    FadeOutDuration = 0.2,
                },
            },
            Minimap      = { Enabled = false },
            Details = {
                Enabled = false,
                detailsBarH = 26,
                detailsSpacing = 1,
                detailsTitelH = 20,
                detailsWidth = 260,
                backDropOne = {
                    Enabled = true,
                    autoSize = false,
                    detailsBars = 8,
                    width = 260,
                    height = 210,
                    BackgroundColor = { 0, 0, 0, 0.8 },
                    BorderColor = { 0, 0, 0, 1 },
                    Strata = "LOW",
                    Position = {
                        AnchorFrom = "BOTTOMRIGHT",
                        AnchorTo = "BOTTOMRIGHT",
                        XOffset = -1,
                        YOffset = 1,
                    },
                },
                backDropTwo = {
                    Enabled = true,
                    autoSize = false,
                    detailsBars = 8,
                    width = 260,
                    height = 210,
                    BackgroundColor = { 0, 0, 0, 0.8 },
                    BorderColor = { 0, 0, 0, 1 },
                    Strata = "LOW",
                    Position = {
                        AnchorFrom = "BOTTOMRIGHT",
                        AnchorTo = "BOTTOMRIGHT",
                        XOffset = -262,
                        YOffset = 1,
                    },
                },
            },
            ActionBars = {
                Enabled = false,
                HideProfTexture = true,
                HideMacroText = false,
                MouseoverOverride = false,
                Mouseover = {
                    Enabled = false,
                    FadeInDuration = 0.3,
                    FadeOutDuration = 1,
                    Alpha = 0,
                },
                FontFace = "Expressway",
                FontOutline = "OUTLINE",
                FontSizes = {
                    KeybindSize = 12,
                    CooldownSize = 14,
                    ChargeSize = 12,
                    MacroSize = 10,
                },
                KeybindAnchor = "TOPRIGHT",
                KeybindXOffset = -2,
                KeybindYOffset = -2,
                ChargeAnchor = "BOTTOMRIGHT",
                ChargeXOffset = -2,
                ChargeYOffset = 2,
                MacroAnchor = "BOTTOM",
                MacroXOffset = 0,
                MacroYOffset = 2,
                CooldownAnchor = "CENTER",
                CooldownXOffset = 0,
                CooldownYOffset = 0,
                Bars = {
                    Bar1 = {
                        Enabled = true, Spacing = 1, ButtonSize = 40, TotalButtons = 12,
                        Layout = "HORIZONTAL", GrowthDirection = "RIGHT", ButtonsPerLine = 12,
                        ParentFrame = "UIParent", HideEmptyBackdrops = false,
                        BackdropColor = { 0, 0, 0, 0.8 }, BorderColor = { 0, 0, 0, 1 },
                        Position = { AnchorFrom = "BOTTOM", AnchorTo = "BOTTOM", XOffset = 0.1, YOffset = 1.1 },
                        Mouseover = { GlobalOverride = true, Enabled = true, Alpha = 0 },
                        FontSizes = { GlobalOverride = true, KeybindSize = 12, CooldownSize = 14, ChargeSize = 12, MacroSize = 10 },
                        TextPositions = { GlobalOverride = true, KeybindAnchor = "TOPRIGHT", KeybindXOffset = -2, KeybindYOffset = -2, ChargeAnchor = "BOTTOMRIGHT", ChargeXOffset = -2, ChargeYOffset = 2, MacroAnchor = "BOTTOM", MacroXOffset = 0, MacroYOffset = -2 },
                    },
                    Bar2 = {
                        Enabled = true, Spacing = 1, ButtonSize = 40, TotalButtons = 12,
                        Layout = "HORIZONTAL", GrowthDirection = "RIGHT", ButtonsPerLine = 6,
                        ParentFrame = "UIParent", HideEmptyBackdrops = false,
                        BackdropColor = { 0, 0, 0, 0.8 }, BorderColor = { 0, 0, 0, 1 },
                        Position = { AnchorFrom = "BOTTOM", AnchorTo = "BOTTOM", XOffset = 369.1, YOffset = 1.1 },
                        Mouseover = { GlobalOverride = true, Enabled = true, Alpha = 0 },
                        FontSizes = { GlobalOverride = true, KeybindSize = 12, CooldownSize = 14, ChargeSize = 12, MacroSize = 10 },
                        TextPositions = { GlobalOverride = true, KeybindAnchor = "TOPRIGHT", KeybindXOffset = -2, KeybindYOffset = -2, ChargeAnchor = "BOTTOMRIGHT", ChargeXOffset = -2, ChargeYOffset = 2, MacroAnchor = "BOTTOM", MacroXOffset = 0, MacroYOffset = -2 },
                    },
                    Bar3 = {
                        Enabled = true, Spacing = 1, ButtonSize = 40, TotalButtons = 12,
                        Layout = "HORIZONTAL", GrowthDirection = "RIGHT", ButtonsPerLine = 12,
                        ParentFrame = "UIParent", HideEmptyBackdrops = false,
                        BackdropColor = { 0, 0, 0, 0.8 }, BorderColor = { 0, 0, 0, 1 },
                        Position = { AnchorFrom = "BOTTOM", AnchorTo = "BOTTOM", XOffset = 0.1, YOffset = 42.1 },
                        Mouseover = { GlobalOverride = true, Enabled = true, Alpha = 0 },
                        FontSizes = { GlobalOverride = true, KeybindSize = 12, CooldownSize = 14, ChargeSize = 12, MacroSize = 10 },
                        TextPositions = { GlobalOverride = true, KeybindAnchor = "TOPRIGHT", KeybindXOffset = -2, KeybindYOffset = -2, ChargeAnchor = "BOTTOMRIGHT", ChargeXOffset = -2, ChargeYOffset = 2, MacroAnchor = "BOTTOM", MacroXOffset = 0, MacroYOffset = -2 },
                    },
                    Bar4 = {
                        Enabled = true, Spacing = 1, ButtonSize = 40, TotalButtons = 12,
                        Layout = "VERTICAL", GrowthDirection = "RIGHT", ButtonsPerLine = 6,
                        ParentFrame = "UIParent", HideEmptyBackdrops = false,
                        BackdropColor = { 0, 0, 0, 0.8 }, BorderColor = { 0, 0, 0, 1 },
                        Position = { AnchorFrom = "BOTTOMLEFT", AnchorTo = "BOTTOMLEFT", XOffset = 450.1, YOffset = 1.1 },
                        Mouseover = { GlobalOverride = true, Enabled = true, Alpha = 0 },
                        FontSizes = { GlobalOverride = true, KeybindSize = 12, CooldownSize = 14, ChargeSize = 12, MacroSize = 10 },
                        TextPositions = { GlobalOverride = true, KeybindAnchor = "TOPRIGHT", KeybindXOffset = -2, KeybindYOffset = -2, ChargeAnchor = "BOTTOMRIGHT", ChargeXOffset = -2, ChargeYOffset = 2, MacroAnchor = "BOTTOM", MacroXOffset = 0, MacroYOffset = -2 },
                    },
                    Bar5 = {
                        Enabled = true, Spacing = 1, ButtonSize = 40, TotalButtons = 12,
                        Layout = "HORIZONTAL", GrowthDirection = "RIGHT", ButtonsPerLine = 6,
                        ParentFrame = "UIParent", HideEmptyBackdrops = false,
                        BackdropColor = { 0, 0, 0, 0.8 }, BorderColor = { 0, 0, 0, 1 },
                        Position = { AnchorFrom = "BOTTOM", AnchorTo = "BOTTOM", XOffset = -368.1, YOffset = 1.1 },
                        Mouseover = { GlobalOverride = true, Enabled = true, Alpha = 0 },
                        FontSizes = { GlobalOverride = true, KeybindSize = 12, CooldownSize = 14, ChargeSize = 12, MacroSize = 10 },
                        TextPositions = { GlobalOverride = true, KeybindAnchor = "TOPRIGHT", KeybindXOffset = -2, KeybindYOffset = -2, ChargeAnchor = "BOTTOMRIGHT", ChargeXOffset = -2, ChargeYOffset = 2, MacroAnchor = "BOTTOM", MacroXOffset = 0, MacroYOffset = -2 },
                    },
                    Bar6 = {
                        Enabled = true, Spacing = 1, ButtonSize = 40, TotalButtons = 12,
                        Layout = "VERTICAL", GrowthDirection = "RIGHT", ButtonsPerLine = 6,
                        ParentFrame = "UIParent", HideEmptyBackdrops = false,
                        BackdropColor = { 0, 0, 0, 0.8 }, BorderColor = { 0, 0, 0, 1 },
                        Position = { AnchorFrom = "BOTTOMLEFT", AnchorTo = "BOTTOMLEFT", XOffset = 532.1, YOffset = 1.1 },
                        Mouseover = { GlobalOverride = true, Enabled = true, Alpha = 0 },
                        FontSizes = { GlobalOverride = true, KeybindSize = 12, CooldownSize = 14, ChargeSize = 12, MacroSize = 10 },
                        TextPositions = { GlobalOverride = true, KeybindAnchor = "TOPRIGHT", KeybindXOffset = -2, KeybindYOffset = -2, ChargeAnchor = "BOTTOMRIGHT", ChargeXOffset = -2, ChargeYOffset = 2, MacroAnchor = "BOTTOM", MacroXOffset = 0, MacroYOffset = -2 },
                    },
                    Bar7 = {
                        Enabled = true, Spacing = 1, ButtonSize = 40, TotalButtons = 12,
                        Layout = "VERTICAL", GrowthDirection = "RIGHT", ButtonsPerLine = 12,
                        ParentFrame = "UIParent", HideEmptyBackdrops = false,
                        BackdropColor = { 0, 0, 0, 0.8 }, BorderColor = { 0, 0, 0, 1 },
                        Position = { AnchorFrom = "LEFT", AnchorTo = "LEFT", XOffset = 1.1, YOffset = 0.1 },
                        Mouseover = { GlobalOverride = true, Enabled = false, Alpha = 1 },
                        FontSizes = { GlobalOverride = true, KeybindSize = 12, CooldownSize = 14, ChargeSize = 12, MacroSize = 10 },
                        TextPositions = { GlobalOverride = true, KeybindAnchor = "TOPRIGHT", KeybindXOffset = -2, KeybindYOffset = -2, ChargeAnchor = "BOTTOMRIGHT", ChargeXOffset = -2, ChargeYOffset = 2, MacroAnchor = "BOTTOM", MacroXOffset = 0, MacroYOffset = -2 },
                    },
                    Bar8 = {
                        Enabled = true, Spacing = 1, ButtonSize = 40, TotalButtons = 12,
                        Layout = "VERTICAL", GrowthDirection = "RIGHT", ButtonsPerLine = 12,
                        ParentFrame = "UIParent", HideEmptyBackdrops = false,
                        BackdropColor = { 0, 0, 0, 0.8 }, BorderColor = { 0, 0, 0, 1 },
                        Position = { AnchorFrom = "LEFT", AnchorTo = "LEFT", XOffset = 42.1, YOffset = 0.1 },
                        Mouseover = { GlobalOverride = true, Enabled = false, Alpha = 1 },
                        FontSizes = { GlobalOverride = true, KeybindSize = 12, CooldownSize = 14, ChargeSize = 12, MacroSize = 10 },
                        TextPositions = { GlobalOverride = true, KeybindAnchor = "TOPRIGHT", KeybindXOffset = -2, KeybindYOffset = -2, ChargeAnchor = "BOTTOMRIGHT", ChargeXOffset = -2, ChargeYOffset = 2, MacroAnchor = "BOTTOM", MacroXOffset = 0, MacroYOffset = -2 },
                    },
                    PetBar = {
                        Enabled = true, Spacing = 1, ButtonSize = 32, TotalButtons = 10,
                        Layout = "HORIZONTAL", GrowthDirection = "RIGHT", ButtonsPerLine = 10,
                        ParentFrame = "UIParent", HideEmptyBackdrops = false,
                        BackdropColor = { 0, 0, 0, 0.8 }, BorderColor = { 0, 0, 0, 1 },
                        Position = { AnchorFrom = "BOTTOM", AnchorTo = "BOTTOM", XOffset = 0.1, YOffset = 83.1 },
                        Mouseover = { GlobalOverride = false, Enabled = false, Alpha = 0 },
                        FontSizes = { GlobalOverride = true, KeybindSize = 10, CooldownSize = 12, ChargeSize = 10, MacroSize = 8 },
                        TextPositions = { GlobalOverride = true, KeybindAnchor = "TOPRIGHT", KeybindXOffset = -2, KeybindYOffset = -2, ChargeAnchor = "BOTTOMRIGHT", ChargeXOffset = -2, ChargeYOffset = 2, MacroAnchor = "BOTTOM", MacroXOffset = 0, MacroYOffset = -2 },
                    },
                    StanceBar = {
                        Enabled = true, Spacing = 1, ButtonSize = 32, TotalButtons = 10,
                        Layout = "HORIZONTAL", GrowthDirection = "RIGHT", ButtonsPerLine = 10,
                        ParentFrame = "UIParent", HideEmptyBackdrops = true,
                        BackdropColor = { 0, 0, 0, 0.8 }, BorderColor = { 0, 0, 0, 1 },
                        Position = { AnchorFrom = "BOTTOM", AnchorTo = "BOTTOM", XOffset = 0.1, YOffset = 117.1 },
                        Mouseover = { GlobalOverride = false, Enabled = false, Alpha = 0 },
                        FontSizes = { GlobalOverride = true, KeybindSize = 10, CooldownSize = 12, ChargeSize = 10, MacroSize = 8 },
                        TextPositions = { GlobalOverride = true, KeybindAnchor = "TOPRIGHT", KeybindXOffset = -2, KeybindYOffset = -2, ChargeAnchor = "BOTTOMRIGHT", ChargeXOffset = -2, ChargeYOffset = 2, MacroAnchor = "BOTTOM", MacroXOffset = 0, MacroYOffset = -2 },
                    },
                },
            },
            Auras = {
                Enabled = false,
                disableFlashing = true,
                FontFace = "Expressway",
                FontOutline = "OUTLINE",
                FontColor = { 1, 1, 1, 1 },
                buffSize = 36,
                buffBorderColor = { 0, 0, 0, 1 },
                debuffSize = 40,
                debuffBorderColor = { 0.8, 0, 0, 1 },
                defSize = 42,
                defBorderColor = { 0, 0, 0, 1 },
            },
            CDMOverlay   = { Enabled = false },
            CDMGlow      = { Enabled = false },
            UICleanup    = { Enabled = false },
            Battlenet    = { Enabled = false },
            RaidManager  = {
                Enabled = false,
                Position = {
                    YOffset = -100,
                },
                Strata = "HIGH",
                FadeOnMouseOut = true,
                FadeInDuration = 0.3,
                FadeOutDuration = 3,
                Alpha = 0,
            },
        },

        ----------------------------------------------------------------
        -- CUSTOM BUFFS
        ----------------------------------------------------------------

        BuffIcons = {
            Enabled = false,
            GrowthDirection = "RIGHT",
            Spacing = 2,
            anchorFrameType = "UIPARENT",
            ParentFrame = "UIParent",
            Position = DefaultPosition(0, 250),
            Trackers = {},
            Defaults = {
                IconSize = 40,
                ShowCooldownText = true,
                CountdownSize = 18,
                BorderColor = { 0, 0, 0, 1 },
                BorderSize = 1,
            },
        },

        BuffBars = {
            Enabled = false,
            GrowthDirection = "DOWN",
            Spacing = 2,
            anchorFrameType = "UIPARENT",
            ParentFrame = "UIParent",
            Position = DefaultPosition(0, 280),
            Trackers = {},
            Defaults = {
                BarWidth = 200,
                BarHeight = 20,
                IconSize = 20,
                ShowIcon = true,
                ShowTimeText = true,
                ShowSpellText = true,
                FontSize = 12,
                BarColor = { 0.65, 0.65, 0.65, 1 },
                BackgroundColor = { 0, 0, 0, 0.8 },
                BorderColor = { 0, 0, 0, 1 },
                Reverse = false,
                StatusBarTexture = "Blizzard",
            },
        },

        ExternalsDefensives = {
            Enabled = false,
            GrowthDirection = "RIGHT",
            Spacing = 2,
            anchorFrameType = "UIPARENT",
            ParentFrame = "UIParent",
            Position = DefaultPosition(0, 300),
            Trackers = {},
            Defaults = {
                IconSize = 40,
                ShowCooldownText = true,
                CountdownSize = 18,
                BorderColor = { 0, 0, 0, 1 },
                BorderSize = 1,
            },
        },

        MovementBuffs = {
            Enabled = false,
            GrowthDirection = "RIGHT",
            Spacing = 2,
            anchorFrameType = "UIPARENT",
            ParentFrame = "UIParent",
            Position = DefaultPosition(0, 250),
            Trackers = {},
            Defaults = {
                IconSize = 40,
                ShowCooldownText = true,
                CountdownSize = 18,
                BorderColor = { 0, 0, 0, 1 },
                BorderSize = 1,
            },
        },
    },
}

function KE:GetDefaultDB()
    return Defaults
end
