-- Tier 1: DungeonTrash cross-data integrity (TrashTraits <-> TrashData).
-- The two data tables are auto-generated by dev/scripts/extract-trash-data.lua
-- from separate ExBoss source structures (per-mob identity vs per-spell timers).
-- If they ever fall out of sync — a mob fingerprinted with no curated spell, a
-- spell with no matchable duration — the engine resolves the mob in-game but
-- fires NOTHING, a silent failure with no stack trace. These specs make that a
-- red CI build instead of a missed alert nobody notices for a season.

local helpers = require("dev.spec._helpers")

local function loadData()
    _G.KitnEssentials = _G.KitnEssentials or {}
    local KE = {}
    helpers.loadModule("Modules/DungeonTimers/Trash/TrashTraits.lua", KE)
    helpers.loadModule("Modules/DungeonTimers/Trash/TrashData.lua", KE)
    return KE
end

describe("DungeonTrash data integrity — TrashTraits <-> TrashData", function()
    local KE, traits, data, mapByNpc, mobByNpc
    setup(function()
        KE = loadData()
        traits, data = KE.TrashTraits, KE.TrashData
        mapByNpc, mobByNpc = {}, {}
        for mapID, d in pairs(data) do
            for npcID, mob in pairs(d.mobs or {}) do
                mapByNpc[npcID] = mapID
                mobByNpc[npcID] = mob
            end
        end
    end)

    it("has both data tables", function()
        assert.is_table(traits)
        assert.is_table(data)
    end)

    it("every fingerprinted mob has curated spell data (else it resolves but never alerts)", function()
        local orphans = {}
        for npcID, t in pairs(traits) do
            local mob = mobByNpc[npcID]
            if not (mob and mob.spells and next(mob.spells)) then
                orphans[#orphans + 1] = string.format("%d (%s / %s)", npcID, t.dungeonKey, t.name or "?")
            end
        end
        assert.same({}, orphans)
    end)

    it("every curated data mob is reachable via a fingerprint (no dead data)", function()
        local unreachable = {}
        for npcID, mob in pairs(mobByNpc) do
            if not traits[npcID] then
                unreachable[#unreachable + 1] = string.format("%d (%s)", npcID, mob.name or "?")
            end
        end
        assert.same({}, unreachable)
    end)

    it("every curated spell has a Layer2-matchable duration (castTime or channelTime > 0)", function()
        local unmatchable = {}
        for npcID, mob in pairs(mobByNpc) do
            for spellID, sp in pairs(mob.spells or {}) do
                local hasDur = (tonumber(sp.castTime) or 0) > 0 or (tonumber(sp.channelTime) or 0) > 0
                if not hasDur then
                    unmatchable[#unmatchable + 1] = string.format("%d/%s (%s)", npcID, tostring(spellID), sp.name or "?")
                end
            end
        end
        assert.same({}, unmatchable)
    end)

    it("every spell's inner spellID matches its table key", function()
        local mismatched = {}
        for npcID, mob in pairs(mobByNpc) do
            for spellID, sp in pairs(mob.spells or {}) do
                if sp.spellID ~= spellID then
                    mismatched[#mismatched + 1] = string.format("%d: key %s != inner %s", npcID, tostring(spellID), tostring(sp.spellID))
                end
            end
        end
        assert.same({}, mismatched)
    end)

    it("traits.mapID and dungeonKey agree with the data table for every mob", function()
        local conflicts = {}
        for npcID, t in pairs(traits) do
            local mapID = mapByNpc[npcID]
            if mapID then
                if mapID ~= t.mapID then
                    conflicts[#conflicts + 1] = string.format("%d mapID traits=%s data=%s", npcID, tostring(t.mapID), tostring(mapID))
                end
                if data[mapID].dungeonKey ~= t.dungeonKey then
                    conflicts[#conflicts + 1] = string.format("%d dungeonKey traits=%s data=%s", npcID, t.dungeonKey, data[mapID].dungeonKey)
                end
            end
        end
        assert.same({}, conflicts)
    end)
end)

-- TrashCurated (the HAND-MAINTAINED overlay) integrity. Its keys and preset
-- names are typed by a human against auto-generated data and a palette in a
-- different file, and every mistake fails SILENTLY in-game: a typo'd
-- mapID/npcID/spellID key no-ops the whole entry, a typo'd label/colorKey
-- degrades the alert to the flat default colour, a typo'd role key drops the
-- restriction. The real DungeonTimers.lua is loaded so labels resolve through
-- the REAL preset/alias tables — no stub to drift.
describe("DungeonTrash data integrity — TrashCurated overlay", function()
    local loader = require("dev.spec._ke_loader")
    local KE2, curated, cdata

    -- Labels DELIBERATELY rendered verbatim in the flat default colour (no
    -- preset/alias match intended). Add here with a reason, or the resolution
    -- test flags them as probable typos.
    local VERBATIM_LABELS = {}

    local ROLE_KEYS = { tank = true, healer = true, dps = true }

    setup(function()
        KE2 = select(2, loader.loadDungeonTimers())
        helpers.loadModule("Modules/DungeonTimers/Trash/TrashData.lua", KE2)
        helpers.loadModule("Modules/DungeonTimers/Trash/TrashCurated.lua", KE2)
        curated, cdata = KE2.TrashCurated, KE2.TrashData
    end)

    it("loads the overlay and the shared palette resolver", function()
        assert.is_table(curated)
        assert.is_function(KE2.ResolveTrashPresetColor)
    end)

    it("every curated key points at a real TrashData spell (a typo silently no-ops)", function()
        local orphans = {}
        for mapID, mobs in pairs(curated) do
            for npcID, spells in pairs(mobs) do
                for spellID in pairs(spells) do
                    local d = cdata[mapID]
                    local mob = d and d.mobs and d.mobs[npcID]
                    if not (mob and mob.spells and mob.spells[spellID]) then
                        orphans[#orphans + 1] = string.format("%s/%s/%s",
                            tostring(mapID), tostring(npcID), tostring(spellID))
                    end
                end
            end
        end
        assert.same({}, orphans)
    end)

    it("every curated label and colorKey resolves to a preset colour", function()
        local misses = {}
        for mapID, mobs in pairs(curated) do
            for npcID, spells in pairs(mobs) do
                for spellID, o in pairs(spells) do
                    if o.colorKey and not KE2.ResolveTrashPresetColor(o.colorKey) then
                        misses[#misses + 1] = string.format("%d/%d/%d colorKey %q",
                            mapID, npcID, spellID, o.colorKey)
                    end
                    if o.label and not VERBATIM_LABELS[o.label]
                        and not KE2.ResolveTrashPresetColor(o.label) then
                        misses[#misses + 1] = string.format("%d/%d/%d label %q",
                            mapID, npcID, spellID, o.label)
                    end
                end
            end
        end
        assert.same({}, misses)
    end)

    it("display values are only 'bar' or 'text', and role tables carry only known keys", function()
        local bad = {}
        for mapID, mobs in pairs(curated) do
            for npcID, spells in pairs(mobs) do
                for spellID, o in pairs(spells) do
                    if o.display ~= nil and o.display ~= "bar" and o.display ~= "text" then
                        bad[#bad + 1] = string.format("%d/%d/%d display %q",
                            mapID, npcID, spellID, tostring(o.display))
                    end
                    if o.roles ~= nil then
                        for k in pairs(o.roles) do
                            if not ROLE_KEYS[k] then
                                bad[#bad + 1] = string.format("%d/%d/%d role key %q",
                                    mapID, npcID, spellID, tostring(k))
                            end
                        end
                    end
                end
            end
        end
        assert.same({}, bad)
    end)
end)
