-- Tier 1: DungeonTrash cross-data integrity (TrashTraits <-> TrashData).
-- The two data tables are auto-generated by dev/scripts/extract-trash-data.lua
-- from separate ExBoss source structures (per-mob identity vs per-spell timers).
-- If they ever fall out of sync — a mob fingerprinted with no curated spell, a
-- spell with no matchable duration — the engine resolves the mob in-game but
-- fires NOTHING, a silent failure with no stack trace. These specs make that a
-- red CI build instead of a missed alert nobody notices for a season.

local helpers = require("dev.spec._helpers")

local function loadData()
    _G.KitnEssentials = _G.KitnEssentials or {}
    local KE = {}
    helpers.loadModule("Modules/DungeonTimers/Trash/TrashTraits.lua", KE)
    helpers.loadModule("Modules/DungeonTimers/Trash/TrashData.lua", KE)
    return KE
end

describe("DungeonTrash data integrity — TrashTraits <-> TrashData", function()
    local KE, traits, data, mapByNpc, mobByNpc
    setup(function()
        KE = loadData()
        traits, data = KE.TrashTraits, KE.TrashData
        mapByNpc, mobByNpc = {}, {}
        for mapID, d in pairs(data) do
            for npcID, mob in pairs(d.mobs or {}) do
                mapByNpc[npcID] = mapID
                mobByNpc[npcID] = mob
            end
        end
    end)

    it("has both data tables", function()
        assert.is_table(traits)
        assert.is_table(data)
    end)

    it("every fingerprinted mob has curated spell data (else it resolves but never alerts)", function()
        local orphans = {}
        for npcID, t in pairs(traits) do
            local mob = mobByNpc[npcID]
            if not (mob and mob.spells and next(mob.spells)) then
                orphans[#orphans + 1] = string.format("%d (%s / %s)", npcID, t.dungeonKey, t.name or "?")
            end
        end
        assert.same({}, orphans)
    end)

    it("every curated data mob is reachable via a fingerprint (no dead data)", function()
        local unreachable = {}
        for npcID, mob in pairs(mobByNpc) do
            if not traits[npcID] then
                unreachable[#unreachable + 1] = string.format("%d (%s)", npcID, mob.name or "?")
            end
        end
        assert.same({}, unreachable)
    end)

    it("every curated spell has a Layer2-matchable duration (castTime or channelTime > 0)", function()
        local unmatchable = {}
        for npcID, mob in pairs(mobByNpc) do
            for spellID, sp in pairs(mob.spells or {}) do
                local hasDur = (tonumber(sp.castTime) or 0) > 0 or (tonumber(sp.channelTime) or 0) > 0
                if not hasDur then
                    unmatchable[#unmatchable + 1] = string.format("%d/%s (%s)", npcID, tostring(spellID), sp.name or "?")
                end
            end
        end
        assert.same({}, unmatchable)
    end)

    it("every spell's inner spellID matches its table key", function()
        local mismatched = {}
        for npcID, mob in pairs(mobByNpc) do
            for spellID, sp in pairs(mob.spells or {}) do
                if sp.spellID ~= spellID then
                    mismatched[#mismatched + 1] = string.format("%d: key %s != inner %s", npcID, tostring(spellID), tostring(sp.spellID))
                end
            end
        end
        assert.same({}, mismatched)
    end)

    it("traits.mapID and dungeonKey agree with the data table for every mob", function()
        local conflicts = {}
        for npcID, t in pairs(traits) do
            local mapID = mapByNpc[npcID]
            if mapID then
                if mapID ~= t.mapID then
                    conflicts[#conflicts + 1] = string.format("%d mapID traits=%s data=%s", npcID, tostring(t.mapID), tostring(mapID))
                end
                if data[mapID].dungeonKey ~= t.dungeonKey then
                    conflicts[#conflicts + 1] = string.format("%d dungeonKey traits=%s data=%s", npcID, t.dungeonKey, data[mapID].dungeonKey)
                end
            end
        end
        assert.same({}, conflicts)
    end)
end)
