-- Tier 1: DungeonTimers Trash curated data shape.
-- TrashData.lua / TrashTraits.lua are machine-generated by
-- dev/scripts/extract-trash-data.lua from the upstream ExBoss tables, but a
-- schema drift (a renamed key, a stringified number, a missing enUS name)
-- fails SILENTLY in-game: a bad dungeonKey never resolves to a sidebar tab,
-- a spell with no `first` never schedules a bar. This walks every entry
-- against the documented schema so a regenerate that breaks shape is caught
-- headlessly instead of in a live key.
--
-- Both files guard on the `KitnEssentials` global (like EncounterData.lua),
-- so we set a truthy stand-in before loading — the data assignment itself
-- needs no WoW API.

local helpers = require("dev.spec._helpers")

-- The eight KE dungeon keys these files may reference, and the mapID each
-- must map to (mirrors DUNGEONS in the extraction script + the sidebar ids).
local MAP_KEY = {
    [658]  = "PitOfSaron",
    [1209] = "Skyreach",
    [1753] = "SeatOfTriumvirate",
    [2526] = "AlgetharAcademy",
    [2805] = "WindrunnerSpire",
    [2811] = "MagistersTerrace",
    [2874] = "MaisaraCaverns",
    [2915] = "NexusPointXenas",
}
local VALID_KEYS = {}
for _, key in pairs(MAP_KEY) do VALID_KEYS[key] = true end

-- Identity fields EXDB._r produces (extraction script IDENTITY_ORDER).
local IDENTITY_NUMS  = { "level", "sex", "power", "classID", "buffCount" }
local IDENTITY_BOOLS = {
    "hasCastSkill", "noCastSkill", "hasCastSpell", "hasChannelSpell",
    "hasInterruptFlag", "cannotInterrupt", "nonElite",
}

local function loadTrash(relpath)
    -- Truthy global so the file's `if not KitnEssentials then return end`
    -- guard passes; the module assigns onto our private KE table.
    _G.KitnEssentials = _G.KitnEssentials or {}
    local KE = {}
    helpers.loadModule(relpath, KE)
    return KE
end

local function isNumberArray(v)
    if type(v) ~= "table" then return false end
    if #v == 0 then return false end
    for i = 1, #v do
        if type(v[i]) ~= "number" then return false end
    end
    return true
end

describe("DungeonTimers TrashData (Modules/DungeonTimers/Trash/TrashData.lua)", function()
    local KE
    setup(function()
        KE = loadTrash("Modules/DungeonTimers/Trash/TrashData.lua")
    end)

    it("assigns a non-empty KE.TrashData table", function()
        assert.is_table(KE.TrashData)
        assert.is_true(next(KE.TrashData) ~= nil)
    end)

    it("keys every dungeon by mapID with a matching valid dungeonKey", function()
        local failures = {}
        for mapID, dungeon in pairs(KE.TrashData) do
            local ctx = "mapID " .. tostring(mapID)
            if type(mapID) ~= "number" then
                failures[#failures + 1] = ctx .. ": map key is not a number"
            end
            if dungeon.mapID ~= mapID then
                failures[#failures + 1] = ctx .. ": inner mapID mismatch (" .. tostring(dungeon.mapID) .. ")"
            end
            if not VALID_KEYS[dungeon.dungeonKey] then
                failures[#failures + 1] = ctx .. ": unknown dungeonKey " .. tostring(dungeon.dungeonKey)
            elseif MAP_KEY[mapID] and dungeon.dungeonKey ~= MAP_KEY[mapID] then
                failures[#failures + 1] = ctx .. ": dungeonKey " .. tostring(dungeon.dungeonKey)
                    .. " != expected " .. MAP_KEY[mapID]
            end
            if type(dungeon.name) ~= "string" or dungeon.name == "" then
                failures[#failures + 1] = ctx .. ": missing English dungeon name"
            end
            if type(dungeon.mobs) ~= "table" or next(dungeon.mobs) == nil then
                failures[#failures + 1] = ctx .. ": no mobs"
            end
        end
        assert.same({}, failures)
    end)

    it("gives every mob a numeric key and a non-empty enUS name", function()
        local failures = {}
        for mapID, dungeon in pairs(KE.TrashData) do
            for npcID, mob in pairs(dungeon.mobs or {}) do
                local ctx = string.format("map %s mob %s", tostring(mapID), tostring(npcID))
                if type(npcID) ~= "number" then
                    failures[#failures + 1] = ctx .. ": mob key is not a number"
                end
                if mob.npcID ~= npcID then
                    failures[#failures + 1] = ctx .. ": inner npcID mismatch (" .. tostring(mob.npcID) .. ")"
                end
                if type(mob.name) ~= "string" or mob.name == "" then
                    failures[#failures + 1] = ctx .. ": missing enUS mob name"
                end
                if type(mob.spells) ~= "table" or next(mob.spells) == nil then
                    failures[#failures + 1] = ctx .. ": no spells"
                end
            end
        end
        assert.same({}, failures)
    end)

    it("shapes every spell: id+name, first-or-hidden, numeric cd, boolean roles", function()
        local failures = {}
        for mapID, dungeon in pairs(KE.TrashData) do
            for npcID, mob in pairs(dungeon.mobs or {}) do
                for spellID, spell in pairs(mob.spells or {}) do
                    local ctx = string.format("map %s mob %s spell %s",
                        tostring(mapID), tostring(npcID), tostring(spellID))

                    if type(spellID) ~= "number" then
                        failures[#failures + 1] = ctx .. ": spell key is not a number"
                    end
                    if spell.spellID ~= spellID then
                        failures[#failures + 1] = ctx .. ": inner spellID mismatch (" .. tostring(spell.spellID) .. ")"
                    end
                    if type(spell.name) ~= "string" or spell.name == "" then
                        failures[#failures + 1] = ctx .. ": missing spell name"
                    end
                    -- Actionable trigger: a scheduled `first`, or an explicit hidden flag.
                    if type(spell.first) ~= "number" and spell.hidden ~= true then
                        failures[#failures + 1] = ctx .. ": needs a numeric `first` or hidden = true"
                    end
                    if spell.cd ~= nil and not isNumberArray(spell.cd) then
                        failures[#failures + 1] = ctx .. ": cd must be a non-empty number array"
                    end
                    if spell.castTimeExtra ~= nil and not isNumberArray(spell.castTimeExtra) then
                        failures[#failures + 1] = ctx .. ": castTimeExtra must be a number array"
                    end

                    -- Display defaults.
                    if type(spell.showNameplate) ~= "boolean" then
                        failures[#failures + 1] = ctx .. ": showNameplate must be a boolean"
                    end
                    if spell.display ~= "bar" and spell.display ~= "text" then
                        failures[#failures + 1] = ctx .. ": display must be \"bar\" or \"text\""
                    end
                    local r = spell.roles
                    if type(r) ~= "table" then
                        failures[#failures + 1] = ctx .. ": missing roles table"
                    else
                        for _, slot in ipairs({ "tank", "healer", "dps" }) do
                            if type(r[slot]) ~= "boolean" then
                                failures[#failures + 1] = ctx .. ": roles." .. slot .. " must be a boolean"
                            end
                        end
                    end
                end
            end
        end
        assert.same({}, failures)
    end)
end)

describe("DungeonTimers TrashTraits (Modules/DungeonTimers/Trash/TrashTraits.lua)", function()
    local KE
    setup(function()
        KE = loadTrash("Modules/DungeonTimers/Trash/TrashTraits.lua")
    end)

    it("assigns a non-empty KE.TrashTraits table", function()
        assert.is_table(KE.TrashTraits)
        assert.is_true(next(KE.TrashTraits) ~= nil)
    end)

    it("shapes every trait: npcID/mapID/dungeonKey, decoded identity, spellIDs", function()
        local failures = {}
        for npcID, trait in pairs(KE.TrashTraits) do
            local ctx = "npc " .. tostring(npcID)
            if type(npcID) ~= "number" then
                failures[#failures + 1] = ctx .. ": trait key is not a number"
            end
            if trait.npcID ~= npcID then
                failures[#failures + 1] = ctx .. ": inner npcID mismatch (" .. tostring(trait.npcID) .. ")"
            end
            if not (MAP_KEY[trait.mapID] and MAP_KEY[trait.mapID] == trait.dungeonKey) then
                failures[#failures + 1] = ctx .. ": mapID/dungeonKey mismatch ("
                    .. tostring(trait.mapID) .. "/" .. tostring(trait.dungeonKey) .. ")"
            end
            if type(trait.identity) ~= "table" then
                failures[#failures + 1] = ctx .. ": missing identity table"
            else
                for _, f in ipairs(IDENTITY_NUMS) do
                    if type(trait.identity[f]) ~= "number" then
                        failures[#failures + 1] = ctx .. ": identity." .. f .. " must be a number"
                    end
                end
                for _, f in ipairs(IDENTITY_BOOLS) do
                    if type(trait.identity[f]) ~= "boolean" then
                        failures[#failures + 1] = ctx .. ": identity." .. f .. " must be a boolean"
                    end
                end
            end
            if type(trait.placement) ~= "string" then
                failures[#failures + 1] = ctx .. ": placement must be a string"
            end
            if not isNumberArray(trait.spellIDs) then
                failures[#failures + 1] = ctx .. ": spellIDs must be a non-empty number array"
            end
            if trait.castTimeSet ~= nil and not isNumberArray(trait.castTimeSet) then
                failures[#failures + 1] = ctx .. ": castTimeSet must be a number array when present"
            end
            if trait.channelTimeSet ~= nil and not isNumberArray(trait.channelTimeSet) then
                failures[#failures + 1] = ctx .. ": channelTimeSet must be a number array when present"
            end
            if type(trait.packedIdentity) ~= "number" then
                failures[#failures + 1] = ctx .. ": packedIdentity must be a number"
            end
        end
        assert.same({}, failures)
    end)
end)
