local L = require("dev.spec._ke_loader")

describe("ProfileManager:RenameProfile", function()
    it("keeps the active profile when renaming a non-active profile", function()
        local PM, _, db = L.loadProfileManager()
        db:SetProfile("A"); db:SetProfile("B"); db:SetProfile("A")
        assert.equal("A", PM:GetCurrentProfile())
        local ok = PM:RenameProfile("B", "C")
        assert.is_true(ok)
        assert.equal("A", PM:GetCurrentProfile())
        assert.is_nil(db.profiles["B"])
        assert.is_table(db.profiles["C"])
    end)

    it("stays on the new name when renaming the active profile", function()
        local PM, _, db = L.loadProfileManager()
        db:SetProfile("A")
        PM:RenameProfile("A", "A2")
        assert.equal("A2", PM:GetCurrentProfile())
        assert.is_nil(db.profiles["A"])
    end)

    it("updates the global-profile pointer when renaming the global profile", function()
        local PM, _, db = L.loadProfileManager()
        db.global.GlobalProfile = "G"
        db:SetProfile("G"); db:SetProfile("Default")
        PM:RenameProfile("G", "G2")
        assert.equal("G2", db.global.GlobalProfile)
    end)
end)
